/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PWRouteImport } from './routes/PW'
import { Route as AeoRankRouteImport } from './routes/aeo-rank'
import { Route as AiSettingsRouteImport } from './routes/ai-settings'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AvisAiGuideRouteImport } from './routes/avis-ai-guide'
import { Route as AvisAiHotelRouteImport } from './routes/avis-ai-hotel'
import { Route as AvisAiRestaurantRouteImport } from './routes/avis-ai-restaurant'
import { Route as BusinessesRouteImport } from './routes/businesses'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ChecklistRouteImport } from './routes/checklist'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ChoosePlanRouteImport } from './routes/choose-plan'
import { Route as CommandesRouteImport } from './routes/commandes'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as GmbAutopostingRouteImport } from './routes/gmb-autoposting'
import { Route as GmbPostRouteImport } from './routes/gmb-post'
import { Route as HotelsRouteImport } from './routes/hotels'
import { Route as InstallRouteImport } from './routes/install'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as LocalAeoRouteImport } from './routes/local-aeo'
import { Route as MapsRankRouteImport } from './routes/maps-rank'
import { Route as MobileAdsRouteImport } from './routes/mobile-ads'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PaymentCanceledRouteImport } from './routes/payment-canceled'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProspectionStickersRouteImport } from './routes/prospection-stickers'
import { Route as QrGratuitRouteImport } from './routes/qr-gratuit'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RestaurantsRouteImport } from './routes/restaurants'
import { Route as ReviewReplyAiGoogleBusinessProfileRouteImport } from './routes/review-reply-ai-google-business-profile'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as SelectPlanRouteImport } from './routes/select-plan'
import { Route as SeoAutopostRouteImport } from './routes/seo-autopost'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as BoutiqueIndexRouteImport } from './routes/boutique/index'
import { Route as BoutiqueNfcRouteImport } from './routes/boutique/nfc'
import { Route as BoutiqueQrImprimeRouteImport } from './routes/boutique/qr-imprime'
import { Route as LpFacebookRouteImport } from './routes/lp/facebook'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as ShopSlugRouteImport } from './routes/shop/$slug'
import { Route as ShopCheckoutRouteImport } from './routes/shop/checkout'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PWRoute = PWRouteImport.update({
  id: '/PW',
  path: '/PW',
  getParentRoute: () => rootRouteImport,
} as any)
const AeoRankRoute = AeoRankRouteImport.update({
  id: '/aeo-rank',
  path: '/aeo-rank',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSettingsRoute = AiSettingsRouteImport.update({
  id: '/ai-settings',
  path: '/ai-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisAiGuideRoute = AvisAiGuideRouteImport.update({
  id: '/avis-ai-guide',
  path: '/avis-ai-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisAiHotelRoute = AvisAiHotelRouteImport.update({
  id: '/avis-ai-hotel',
  path: '/avis-ai-hotel',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisAiRestaurantRoute = AvisAiRestaurantRouteImport.update({
  id: '/avis-ai-restaurant',
  path: '/avis-ai-restaurant',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesRoute = BusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ChoosePlanRoute = ChoosePlanRouteImport.update({
  id: '/choose-plan',
  path: '/choose-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandesRoute = CommandesRouteImport.update({
  id: '/commandes',
  path: '/commandes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GmbAutopostingRoute = GmbAutopostingRouteImport.update({
  id: '/gmb-autoposting',
  path: '/gmb-autoposting',
  getParentRoute: () => rootRouteImport,
} as any)
const GmbPostRoute = GmbPostRouteImport.update({
  id: '/gmb-post',
  path: '/gmb-post',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsRoute = HotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalAeoRoute = LocalAeoRouteImport.update({
  id: '/local-aeo',
  path: '/local-aeo',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsRankRoute = MapsRankRouteImport.update({
  id: '/maps-rank',
  path: '/maps-rank',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileAdsRoute = MobileAdsRouteImport.update({
  id: '/mobile-ads',
  path: '/mobile-ads',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCanceledRoute = PaymentCanceledRouteImport.update({
  id: '/payment-canceled',
  path: '/payment-canceled',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectionStickersRoute = ProspectionStickersRouteImport.update({
  id: '/prospection-stickers',
  path: '/prospection-stickers',
  getParentRoute: () => rootRouteImport,
} as any)
const QrGratuitRoute = QrGratuitRouteImport.update({
  id: '/qr-gratuit',
  path: '/qr-gratuit',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsRoute = RestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewReplyAiGoogleBusinessProfileRoute =
  ReviewReplyAiGoogleBusinessProfileRouteImport.update({
    id: '/review-reply-ai-google-business-profile',
    path: '/review-reply-ai-google-business-profile',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectPlanRoute = SelectPlanRouteImport.update({
  id: '/select-plan',
  path: '/select-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoAutopostRoute = SeoAutopostRouteImport.update({
  id: '/seo-autopost',
  path: '/seo-autopost',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueIndexRoute = BoutiqueIndexRouteImport.update({
  id: '/boutique/',
  path: '/boutique/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueNfcRoute = BoutiqueNfcRouteImport.update({
  id: '/boutique/nfc',
  path: '/boutique/nfc',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueQrImprimeRoute = BoutiqueQrImprimeRouteImport.update({
  id: '/boutique/qr-imprime',
  path: '/boutique/qr-imprime',
  getParentRoute: () => rootRouteImport,
} as any)
const LpFacebookRoute = LpFacebookRouteImport.update({
  id: '/lp/facebook',
  path: '/lp/facebook',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCheckoutRoute = ShopCheckoutRouteImport.update({
  id: '/shop/checkout',
  path: '/shop/checkout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/PW': typeof PWRoute
  '/aeo-rank': typeof AeoRankRoute
  '/ai-settings': typeof AiSettingsRoute
  '/auth': typeof AuthRoute
  '/avis-ai-guide': typeof AvisAiGuideRoute
  '/avis-ai-hotel': typeof AvisAiHotelRoute
  '/avis-ai-restaurant': typeof AvisAiRestaurantRoute
  '/businesses': typeof BusinessesRoute
  '/calendar': typeof CalendarRoute
  '/checklist': typeof ChecklistRoute
  '/checkout': typeof CheckoutRoute
  '/choose-plan': typeof ChoosePlanRoute
  '/commandes': typeof CommandesRoute
  '/dashboard': typeof DashboardRoute
  '/gmb-autoposting': typeof GmbAutopostingRoute
  '/gmb-post': typeof GmbPostRoute
  '/hotels': typeof HotelsRoute
  '/install': typeof InstallRoute
  '/landing': typeof LandingRoute
  '/local-aeo': typeof LocalAeoRoute
  '/maps-rank': typeof MapsRankRoute
  '/mobile-ads': typeof MobileAdsRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/payment-canceled': typeof PaymentCanceledRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/privacy': typeof PrivacyRoute
  '/prospection-stickers': typeof ProspectionStickersRoute
  '/qr-gratuit': typeof QrGratuitRoute
  '/reset-password': typeof ResetPasswordRoute
  '/restaurants': typeof RestaurantsRoute
  '/review-reply-ai-google-business-profile': typeof ReviewReplyAiGoogleBusinessProfileRoute
  '/reviews': typeof ReviewsRoute
  '/select-plan': typeof SelectPlanRoute
  '/seo-autopost': typeof SeoAutopostRoute
  '/settings': typeof SettingsRoute
  '/sitemap': typeof SitemapRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/boutique/nfc': typeof BoutiqueNfcRoute
  '/boutique/qr-imprime': typeof BoutiqueQrImprimeRoute
  '/lp/facebook': typeof LpFacebookRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop/checkout': typeof ShopCheckoutRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/boutique/': typeof BoutiqueIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/PW': typeof PWRoute
  '/aeo-rank': typeof AeoRankRoute
  '/ai-settings': typeof AiSettingsRoute
  '/auth': typeof AuthRoute
  '/avis-ai-guide': typeof AvisAiGuideRoute
  '/avis-ai-hotel': typeof AvisAiHotelRoute
  '/avis-ai-restaurant': typeof AvisAiRestaurantRoute
  '/businesses': typeof BusinessesRoute
  '/calendar': typeof CalendarRoute
  '/checklist': typeof ChecklistRoute
  '/checkout': typeof CheckoutRoute
  '/choose-plan': typeof ChoosePlanRoute
  '/commandes': typeof CommandesRoute
  '/dashboard': typeof DashboardRoute
  '/gmb-autoposting': typeof GmbAutopostingRoute
  '/gmb-post': typeof GmbPostRoute
  '/hotels': typeof HotelsRoute
  '/install': typeof InstallRoute
  '/landing': typeof LandingRoute
  '/local-aeo': typeof LocalAeoRoute
  '/maps-rank': typeof MapsRankRoute
  '/mobile-ads': typeof MobileAdsRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/payment-canceled': typeof PaymentCanceledRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/privacy': typeof PrivacyRoute
  '/prospection-stickers': typeof ProspectionStickersRoute
  '/qr-gratuit': typeof QrGratuitRoute
  '/reset-password': typeof ResetPasswordRoute
  '/restaurants': typeof RestaurantsRoute
  '/review-reply-ai-google-business-profile': typeof ReviewReplyAiGoogleBusinessProfileRoute
  '/reviews': typeof ReviewsRoute
  '/select-plan': typeof SelectPlanRoute
  '/seo-autopost': typeof SeoAutopostRoute
  '/settings': typeof SettingsRoute
  '/sitemap': typeof SitemapRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/boutique/nfc': typeof BoutiqueNfcRoute
  '/boutique/qr-imprime': typeof BoutiqueQrImprimeRoute
  '/lp/facebook': typeof LpFacebookRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop/checkout': typeof ShopCheckoutRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/boutique': typeof BoutiqueIndexRoute
  '/shop': typeof ShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/PW': typeof PWRoute
  '/aeo-rank': typeof AeoRankRoute
  '/ai-settings': typeof AiSettingsRoute
  '/auth': typeof AuthRoute
  '/avis-ai-guide': typeof AvisAiGuideRoute
  '/avis-ai-hotel': typeof AvisAiHotelRoute
  '/avis-ai-restaurant': typeof AvisAiRestaurantRoute
  '/businesses': typeof BusinessesRoute
  '/calendar': typeof CalendarRoute
  '/checklist': typeof ChecklistRoute
  '/checkout': typeof CheckoutRoute
  '/choose-plan': typeof ChoosePlanRoute
  '/commandes': typeof CommandesRoute
  '/dashboard': typeof DashboardRoute
  '/gmb-autoposting': typeof GmbAutopostingRoute
  '/gmb-post': typeof GmbPostRoute
  '/hotels': typeof HotelsRoute
  '/install': typeof InstallRoute
  '/landing': typeof LandingRoute
  '/local-aeo': typeof LocalAeoRoute
  '/maps-rank': typeof MapsRankRoute
  '/mobile-ads': typeof MobileAdsRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/payment-canceled': typeof PaymentCanceledRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/privacy': typeof PrivacyRoute
  '/prospection-stickers': typeof ProspectionStickersRoute
  '/qr-gratuit': typeof QrGratuitRoute
  '/reset-password': typeof ResetPasswordRoute
  '/restaurants': typeof RestaurantsRoute
  '/review-reply-ai-google-business-profile': typeof ReviewReplyAiGoogleBusinessProfileRoute
  '/reviews': typeof ReviewsRoute
  '/select-plan': typeof SelectPlanRoute
  '/seo-autopost': typeof SeoAutopostRoute
  '/settings': typeof SettingsRoute
  '/sitemap': typeof SitemapRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/boutique/nfc': typeof BoutiqueNfcRoute
  '/boutique/qr-imprime': typeof BoutiqueQrImprimeRoute
  '/lp/facebook': typeof LpFacebookRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop/checkout': typeof ShopCheckoutRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/boutique/': typeof BoutiqueIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/PW'
    | '/aeo-rank'
    | '/ai-settings'
    | '/auth'
    | '/avis-ai-guide'
    | '/avis-ai-hotel'
    | '/avis-ai-restaurant'
    | '/businesses'
    | '/calendar'
    | '/checklist'
    | '/checkout'
    | '/choose-plan'
    | '/commandes'
    | '/dashboard'
    | '/gmb-autoposting'
    | '/gmb-post'
    | '/hotels'
    | '/install'
    | '/landing'
    | '/local-aeo'
    | '/maps-rank'
    | '/mobile-ads'
    | '/notifications'
    | '/onboarding'
    | '/payment-canceled'
    | '/payment-success'
    | '/privacy'
    | '/prospection-stickers'
    | '/qr-gratuit'
    | '/reset-password'
    | '/restaurants'
    | '/review-reply-ai-google-business-profile'
    | '/reviews'
    | '/select-plan'
    | '/seo-autopost'
    | '/settings'
    | '/sitemap'
    | '/terms'
    | '/unsubscribe'
    | '/admin/orders'
    | '/blog/$slug'
    | '/boutique/nfc'
    | '/boutique/qr-imprime'
    | '/lp/facebook'
    | '/shop/$slug'
    | '/shop/checkout'
    | '/admin/'
    | '/blog/'
    | '/boutique/'
    | '/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/PW'
    | '/aeo-rank'
    | '/ai-settings'
    | '/auth'
    | '/avis-ai-guide'
    | '/avis-ai-hotel'
    | '/avis-ai-restaurant'
    | '/businesses'
    | '/calendar'
    | '/checklist'
    | '/checkout'
    | '/choose-plan'
    | '/commandes'
    | '/dashboard'
    | '/gmb-autoposting'
    | '/gmb-post'
    | '/hotels'
    | '/install'
    | '/landing'
    | '/local-aeo'
    | '/maps-rank'
    | '/mobile-ads'
    | '/notifications'
    | '/onboarding'
    | '/payment-canceled'
    | '/payment-success'
    | '/privacy'
    | '/prospection-stickers'
    | '/qr-gratuit'
    | '/reset-password'
    | '/restaurants'
    | '/review-reply-ai-google-business-profile'
    | '/reviews'
    | '/select-plan'
    | '/seo-autopost'
    | '/settings'
    | '/sitemap'
    | '/terms'
    | '/unsubscribe'
    | '/admin/orders'
    | '/blog/$slug'
    | '/boutique/nfc'
    | '/boutique/qr-imprime'
    | '/lp/facebook'
    | '/shop/$slug'
    | '/shop/checkout'
    | '/admin'
    | '/blog'
    | '/boutique'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/PW'
    | '/aeo-rank'
    | '/ai-settings'
    | '/auth'
    | '/avis-ai-guide'
    | '/avis-ai-hotel'
    | '/avis-ai-restaurant'
    | '/businesses'
    | '/calendar'
    | '/checklist'
    | '/checkout'
    | '/choose-plan'
    | '/commandes'
    | '/dashboard'
    | '/gmb-autoposting'
    | '/gmb-post'
    | '/hotels'
    | '/install'
    | '/landing'
    | '/local-aeo'
    | '/maps-rank'
    | '/mobile-ads'
    | '/notifications'
    | '/onboarding'
    | '/payment-canceled'
    | '/payment-success'
    | '/privacy'
    | '/prospection-stickers'
    | '/qr-gratuit'
    | '/reset-password'
    | '/restaurants'
    | '/review-reply-ai-google-business-profile'
    | '/reviews'
    | '/select-plan'
    | '/seo-autopost'
    | '/settings'
    | '/sitemap'
    | '/terms'
    | '/unsubscribe'
    | '/admin/orders'
    | '/blog/$slug'
    | '/boutique/nfc'
    | '/boutique/qr-imprime'
    | '/lp/facebook'
    | '/shop/$slug'
    | '/shop/checkout'
    | '/admin/'
    | '/blog/'
    | '/boutique/'
    | '/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PWRoute: typeof PWRoute
  AeoRankRoute: typeof AeoRankRoute
  AiSettingsRoute: typeof AiSettingsRoute
  AuthRoute: typeof AuthRoute
  AvisAiGuideRoute: typeof AvisAiGuideRoute
  AvisAiHotelRoute: typeof AvisAiHotelRoute
  AvisAiRestaurantRoute: typeof AvisAiRestaurantRoute
  BusinessesRoute: typeof BusinessesRoute
  CalendarRoute: typeof CalendarRoute
  ChecklistRoute: typeof ChecklistRoute
  CheckoutRoute: typeof CheckoutRoute
  ChoosePlanRoute: typeof ChoosePlanRoute
  CommandesRoute: typeof CommandesRoute
  DashboardRoute: typeof DashboardRoute
  GmbAutopostingRoute: typeof GmbAutopostingRoute
  GmbPostRoute: typeof GmbPostRoute
  HotelsRoute: typeof HotelsRoute
  InstallRoute: typeof InstallRoute
  LandingRoute: typeof LandingRoute
  LocalAeoRoute: typeof LocalAeoRoute
  MapsRankRoute: typeof MapsRankRoute
  MobileAdsRoute: typeof MobileAdsRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  PaymentCanceledRoute: typeof PaymentCanceledRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  PrivacyRoute: typeof PrivacyRoute
  ProspectionStickersRoute: typeof ProspectionStickersRoute
  QrGratuitRoute: typeof QrGratuitRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RestaurantsRoute: typeof RestaurantsRoute
  ReviewReplyAiGoogleBusinessProfileRoute: typeof ReviewReplyAiGoogleBusinessProfileRoute
  ReviewsRoute: typeof ReviewsRoute
  SelectPlanRoute: typeof SelectPlanRoute
  SeoAutopostRoute: typeof SeoAutopostRoute
  SettingsRoute: typeof SettingsRoute
  SitemapRoute: typeof SitemapRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BoutiqueNfcRoute: typeof BoutiqueNfcRoute
  BoutiqueQrImprimeRoute: typeof BoutiqueQrImprimeRoute
  LpFacebookRoute: typeof LpFacebookRoute
  ShopSlugRoute: typeof ShopSlugRoute
  ShopCheckoutRoute: typeof ShopCheckoutRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  BoutiqueIndexRoute: typeof BoutiqueIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/PW': {
      id: '/PW'
      path: '/PW'
      fullPath: '/PW'
      preLoaderRoute: typeof PWRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aeo-rank': {
      id: '/aeo-rank'
      path: '/aeo-rank'
      fullPath: '/aeo-rank'
      preLoaderRoute: typeof AeoRankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-settings': {
      id: '/ai-settings'
      path: '/ai-settings'
      fullPath: '/ai-settings'
      preLoaderRoute: typeof AiSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avis-ai-guide': {
      id: '/avis-ai-guide'
      path: '/avis-ai-guide'
      fullPath: '/avis-ai-guide'
      preLoaderRoute: typeof AvisAiGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avis-ai-hotel': {
      id: '/avis-ai-hotel'
      path: '/avis-ai-hotel'
      fullPath: '/avis-ai-hotel'
      preLoaderRoute: typeof AvisAiHotelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avis-ai-restaurant': {
      id: '/avis-ai-restaurant'
      path: '/avis-ai-restaurant'
      fullPath: '/avis-ai-restaurant'
      preLoaderRoute: typeof AvisAiRestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses': {
      id: '/businesses'
      path: '/businesses'
      fullPath: '/businesses'
      preLoaderRoute: typeof BusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/choose-plan': {
      id: '/choose-plan'
      path: '/choose-plan'
      fullPath: '/choose-plan'
      preLoaderRoute: typeof ChoosePlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commandes': {
      id: '/commandes'
      path: '/commandes'
      fullPath: '/commandes'
      preLoaderRoute: typeof CommandesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gmb-autoposting': {
      id: '/gmb-autoposting'
      path: '/gmb-autoposting'
      fullPath: '/gmb-autoposting'
      preLoaderRoute: typeof GmbAutopostingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gmb-post': {
      id: '/gmb-post'
      path: '/gmb-post'
      fullPath: '/gmb-post'
      preLoaderRoute: typeof GmbPostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels': {
      id: '/hotels'
      path: '/hotels'
      fullPath: '/hotels'
      preLoaderRoute: typeof HotelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local-aeo': {
      id: '/local-aeo'
      path: '/local-aeo'
      fullPath: '/local-aeo'
      preLoaderRoute: typeof LocalAeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps-rank': {
      id: '/maps-rank'
      path: '/maps-rank'
      fullPath: '/maps-rank'
      preLoaderRoute: typeof MapsRankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-ads': {
      id: '/mobile-ads'
      path: '/mobile-ads'
      fullPath: '/mobile-ads'
      preLoaderRoute: typeof MobileAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-canceled': {
      id: '/payment-canceled'
      path: '/payment-canceled'
      fullPath: '/payment-canceled'
      preLoaderRoute: typeof PaymentCanceledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospection-stickers': {
      id: '/prospection-stickers'
      path: '/prospection-stickers'
      fullPath: '/prospection-stickers'
      preLoaderRoute: typeof ProspectionStickersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-gratuit': {
      id: '/qr-gratuit'
      path: '/qr-gratuit'
      fullPath: '/qr-gratuit'
      preLoaderRoute: typeof QrGratuitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants': {
      id: '/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof RestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review-reply-ai-google-business-profile': {
      id: '/review-reply-ai-google-business-profile'
      path: '/review-reply-ai-google-business-profile'
      fullPath: '/review-reply-ai-google-business-profile'
      preLoaderRoute: typeof ReviewReplyAiGoogleBusinessProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-plan': {
      id: '/select-plan'
      path: '/select-plan'
      fullPath: '/select-plan'
      preLoaderRoute: typeof SelectPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-autopost': {
      id: '/seo-autopost'
      path: '/seo-autopost'
      fullPath: '/seo-autopost'
      preLoaderRoute: typeof SeoAutopostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique/': {
      id: '/boutique/'
      path: '/boutique'
      fullPath: '/boutique/'
      preLoaderRoute: typeof BoutiqueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique/nfc': {
      id: '/boutique/nfc'
      path: '/boutique/nfc'
      fullPath: '/boutique/nfc'
      preLoaderRoute: typeof BoutiqueNfcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique/qr-imprime': {
      id: '/boutique/qr-imprime'
      path: '/boutique/qr-imprime'
      fullPath: '/boutique/qr-imprime'
      preLoaderRoute: typeof BoutiqueQrImprimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp/facebook': {
      id: '/lp/facebook'
      path: '/lp/facebook'
      fullPath: '/lp/facebook'
      preLoaderRoute: typeof LpFacebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/checkout': {
      id: '/shop/checkout'
      path: '/shop/checkout'
      fullPath: '/shop/checkout'
      preLoaderRoute: typeof ShopCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PWRoute: PWRoute,
  AeoRankRoute: AeoRankRoute,
  AiSettingsRoute: AiSettingsRoute,
  AuthRoute: AuthRoute,
  AvisAiGuideRoute: AvisAiGuideRoute,
  AvisAiHotelRoute: AvisAiHotelRoute,
  AvisAiRestaurantRoute: AvisAiRestaurantRoute,
  BusinessesRoute: BusinessesRoute,
  CalendarRoute: CalendarRoute,
  ChecklistRoute: ChecklistRoute,
  CheckoutRoute: CheckoutRoute,
  ChoosePlanRoute: ChoosePlanRoute,
  CommandesRoute: CommandesRoute,
  DashboardRoute: DashboardRoute,
  GmbAutopostingRoute: GmbAutopostingRoute,
  GmbPostRoute: GmbPostRoute,
  HotelsRoute: HotelsRoute,
  InstallRoute: InstallRoute,
  LandingRoute: LandingRoute,
  LocalAeoRoute: LocalAeoRoute,
  MapsRankRoute: MapsRankRoute,
  MobileAdsRoute: MobileAdsRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  PaymentCanceledRoute: PaymentCanceledRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  PrivacyRoute: PrivacyRoute,
  ProspectionStickersRoute: ProspectionStickersRoute,
  QrGratuitRoute: QrGratuitRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RestaurantsRoute: RestaurantsRoute,
  ReviewReplyAiGoogleBusinessProfileRoute:
    ReviewReplyAiGoogleBusinessProfileRoute,
  ReviewsRoute: ReviewsRoute,
  SelectPlanRoute: SelectPlanRoute,
  SeoAutopostRoute: SeoAutopostRoute,
  SettingsRoute: SettingsRoute,
  SitemapRoute: SitemapRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  BlogSlugRoute: BlogSlugRoute,
  BoutiqueNfcRoute: BoutiqueNfcRoute,
  BoutiqueQrImprimeRoute: BoutiqueQrImprimeRoute,
  LpFacebookRoute: LpFacebookRoute,
  ShopSlugRoute: ShopSlugRoute,
  ShopCheckoutRoute: ShopCheckoutRoute,
  AdminIndexRoute: AdminIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  BoutiqueIndexRoute: BoutiqueIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
